### ISSUE TITLE
Extract 'httpfile' to module and remove 'curl' dependency

### ISSUE THREAD

**Issue by Iristyle** [basho-labs/puppet-riak#11]
I did a little looking, and apparently it's pretty common for packages to end up being accidentally redeclared.

From my Puppet console output

```
←[1;31mError: Duplicate declaration: Package[curl] is already declared in file /tmp/vagrant-puppet/modules-0/redis/manifests/init.pp at line 9; cannot redeclare on node ubuntu-12.04.2-server-amd64-mono-nginx-node←[0m

←[1;31mError: Duplicate declaration: Package[curl] is already declared in file /tmp/vagrant-puppet/modules-0/redis/manifests/init.pp at line 9; cannot redeclare on node ubuntu-12.04.2-server-amd64-mono-nginx-node←[0m
```

I'm using https://github.com/logicalparadox/puppet-redis to install Redis.

In my Puppet file, I'm installing Redis first, then Riak.

Now, if I reorder how my packages are called in my Puppet script to install Riak first and then Redis, it works just fine.

If you look at the `init.pp` for Redis
https://github.com/logicalparadox/puppet-redis/blob/master/manifests/init.pp#L6

It has the code to prevent the re-declaration.

```puppet
if defined(Package['curl']) == false {
    package { "curl":
      ensure => "installed"
    }
  }
```

So I think that this is all that needs to be added to this package as well...but I'm not a Puppet guy ;0

BTW - This is a demo / Vagrant box and not a real production box -- definitely wouldn't run servers with Riak and Redis on them ;0

**Comment by danieldreier** [comment]
It's been a while since this was reported, so I wanted to re-affirm that this is still a problem. maestrodev/wget is a good option for replacing the homebrew one in this module.

**Comment by haf** [comment]
Done
