### ISSUE TITLE
Please check tarball on Puppet Forge

### ISSUE THREAD

**Issue by L2G** [basho-labs/puppet-riak#24]
This may or may not be of concern to you.

The tarball hosted on [Puppet Forge](http://forge.puppetlabs.com/haf/riak) uses "SCHILY.*" extensions, which causes GNU tar 1.15.1 (the version on Puppet's "learning" VM) to choke on it:

```
[root@learn ~]# puppet module install haf-riak
Notice: Preparing to install into /etc/puppetlabs/puppet/modules ...
Notice: Downloading from https://forge.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
Error: Could not extract contents of module archive: Execution of 'tar xzf /var/opt/lib/pe-puppet/puppet-module/cache/https_forge_puppetlabs_com-ed3a0e51b3c1d8d395ffb1d12c849e3f50d35a10/haf-riak-0.1.1.tar.gz --no-same-permissions --no-same-owner -C /var/opt/lib/pe-puppet/puppet-module/cache/tmp-unpacker-26c36bcd30dc20caedeb577a8304b7092bc92717' returned 2: tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
...
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
tar: Error exit delayed from previous errors

Error: Try 'puppet help module install' for usage
```

I am still new to Puppet, so I don't know whether there's a way to tell `puppet module` to use star instead of tar in order to work around this.

**Comment by mjbrender** [comment]
Not sure how to move this along. Just tagging @danieldreier as FYI! Leaving as backlog for now.

**Comment by danieldreier** [comment]
longer term the answer here is to build for releases as part of a CI process, so we at least have a consistent path / source for build artifacts. If we refactor around [puppet-module-skeleton](https://github.com/garethr/puppet-module-skeleton) we'll get a rakefile that has everything we need for it, and then will just need to figure out where to securely host that. That would probably look something like having a jenkins box at Basho watch the github repo, and then package and publish when releases are tagged in github. That way the puppet forge credentials don't have to be in the public repo or shared with community contributors.

**Comment by danieldreier** [comment]
I'm closing this because the module has been republished as [basholabs/riak](https://forge.puppetlabs.com/basholabs/riak) with a new codebase, and at least one new version of the learning VM has been issued since this was reported.

If this is still a problem for you, please feel free to re-open the issue, though we should also file a ticket against the learning VM if it's still happening.
