### ISSUE TITLE
Specs broken

### ISSUE THREAD

**Issue by L2G** [basho-labs/puppet-riak#35]
Am I running the specs incorrectly? Please see the Travis output at the link below. I have also run the specs on my laptop and within a VM on my laptop, and the results are nearly identical.

https://travis-ci.org/L2G/puppet-riak/builds/19171821

**Comment by mjbrender** [comment]
Hey @L2G or @haf - any improvements here? I'll factor this issue into the community rating for this code. You can see what we're trying to achieve here: https://github.com/basho-labs/the-riak-community/blob/master/config-mgmt-strategy.md

I'd love your help if you still have the need :+1:

**Comment by danieldreier** [comment]
I re-ran specs on ruby 2.1.5 by doing a `bundle install` and a `bundle exec rake specs`. All tests failed, so this is still a valid issue. Not blaming anybody; rspec-puppet with hiera is something I've never managed to get working. I know it's possible, just have't made it work myself.

**Comment by mjbrender** [comment]
Moving as Ready then!

**Comment by danieldreier** [comment]
this will be resolved if https://github.com/basho-labs/puppet-riak/pull/52 is merged because that has passing tests.

**Comment by danieldreier** [comment]
Closing because https://github.com/basho-labs/puppet-riak/pull/52 was merged. Tests now pass, although until https://github.com/basho-labs/puppet-riak/issues/54 is addressed the link to travis results will be broken.
