### ISSUE TITLE
is anybody actually using httpfile?

### ISSUE THREAD

**Issue by danieldreier** [basho-labs/puppet-riak#50]
Rather than [refactoring the httpfile resource](https://github.com/basho-labs/puppet-riak/issues/11) out, can we simply remove httpfile entirely? I'm guessing somebody out there is using it, but wanted to check before we simply grandfather than installation mode in. It seems like any packages would be in a repo anyway; is this there to support the EE install?

**Comment by mjbrender** [comment]
@haf, let's discuss this here. If you don't know of a case, I'd like to go forward w/ @danieldreier's recommendation.

**Comment by haf** [comment]
You can remove it if you want. I think most use packages of Riak now.

**Comment by mjbrender** [comment]
Moving this to Ready based on discussion.

**Comment by danieldreier** [comment]
This will be resolved if https://github.com/basho-labs/puppet-riak/pull/52 is merged because that removes the httpfile code.

**Comment by danieldreier** [comment]
https://github.com/basho-labs/puppet-riak/pull/52 was merged, so this is moot - the resource was removed.
