### ISSUE TITLE
travis-ci not enabled on this repo

### ISSUE THREAD

**Issue by danieldreier** [basho-labs/puppet-riak#54]
@mjbrender can you enable travis-ci tests on this repo at https://travis-ci.org/profile/basho-labs? I don't seem to have access rights.

**Comment by mjbrender** [comment]
Working on it right now and trying to correct it. You should be on the committer list @danieldreier

**Comment by mjbrender** [comment]
Is it looking good?

**Comment by danieldreier** [comment]
I'm on the committer list, but Travis says I'd have to be a repository admin in order to enable it. If you go to https://travis-ci.org/profile/basho-labs you (as admin) should be able to enable tests on the repo directly.

**Comment by mjbrender** [comment]
np - all set now @danieldreier
