### ISSUE TITLE
Get this onto Forge

### ISSUE THREAD

**Issue by mjbrender** [basho-labs/puppet-riak#56]
We have an account at https://forge.puppetlabs.com/users/basholabs. I'm trying to get it going with `puppet module build` and running into some errors: 

     An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
     Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

It's installing just fine. Getting stumped and could use a hand.

**Comment by danieldreier** [comment]
https://github.com/basho-labs/puppet-riak/pull/57 seems relevant, though it doesn't address your specific issue.

Try running a `bundle exec rake build` to get it all running inside the bundler environment.

**Comment by mjbrender** [comment]
@danieldreier failing on `bundle install` before the `bundle exec rake build`.

**Comment by danieldreier** [comment]
I'm going to close this because we're [on the forge](https://forge.puppetlabs.com/basholabs/riak). Let's continue to troubleshooting elsewhere, though.
